"""
Submission-Ready Agent for Pokémon TCG AI Battle Challenge (Simulation Category)

Contract (official engine):
  def agent(obs_dict: dict) -> list[int]:
      - First call (obs.select is None): return 60 card IDs (deck)
      - Subsequent calls: return indices into obs.select.option

This agent wraps our threat-aware heuristic and optimized Team Rocket deck
into the official API format. It is designed to be the entry point for
Kaggle submission.

Submission bundle:
  main.py (= this file, renamed)
  deck.csv (= deck_card_ids.csv, generated by this script)
  cg/ (= official engine bindings, provided by competition)

Strategy: Team Rocket Control — Big Basics with tribal synergy engine.
Anchor: Team Rocket's Mewtwo ex (280 HP, 160 dmg, 3 energy).
Expected Elo: ~1200-1300 based on simulator matchups (52% vs Aggro, 100% vs Evolution).

See kaggle_writeup.md for full strategy rationale.
"""

import csv
import re
import os
import random
from typing import Optional
from collections import defaultdict

# ═══════════════════════════════════════════════════════════════════════════════
# Card Pool & Deck
# ═══════════════════════════════════════════════════════════════════════════════

# Optimized Team Rocket Control deck — 60 card IDs
# These are verified card names from EN_Card_Data.csv
DECK_CARD_NAMES = [
    # Anchor attackers (4 copies each)
    "Team Rocket's Mewtwo ex",      # 4x — 280 HP, 160 dmg
    "Team Rocket's Mewtwo ex",
    "Team Rocket's Mewtwo ex",
    "Team Rocket's Mewtwo ex",
    # Secondary attackers
    "Team Rocket's Kangaskhan ex",   # 4x — 230 HP, 120 dmg
    "Team Rocket's Kangaskhan ex",
    "Team Rocket's Kangaskhan ex",
    "Team Rocket's Kangaskhan ex",
    # Additional threats
    "Team Rocket's Articuno",        # 4x — 120 HP, 60 dmg
    "Team Rocket's Articuno",
    "Team Rocket's Articuno",
    "Team Rocket's Articuno",
    "Team Rocket's Zapdos",          # 4x — 120 HP, 60 dmg
    "Team Rocket's Zapdos",
    "Team Rocket's Zapdos",
    "Team Rocket's Zapdos",
    "Team Rocket's Houndoom",        # 4x — 110 HP, eco attacker
    "Team Rocket's Houndoom",
    "Team Rocket's Houndoom",
    "Team Rocket's Houndoom",
    # Bench fillers (high-HP Rocket basics)
    "Team Rocket's Houndour",        # 2x
    "Team Rocket's Houndour",
    "Team Rocket's Larvitar",        # 2x
    "Team Rocket's Larvitar",
    # Trainers (4 copies each)
    "Ultra Ball",                    # 4x — search engine
    "Ultra Ball",
    "Ultra Ball",
    "Ultra Ball",
    "Boss's Orders",                 # 4x — gust effect
    "Boss's Orders",
    "Boss's Orders",
    "Boss's Orders",
    "Team Rocket's Ariana",          # 4x — Rocket draw
    "Team Rocket's Ariana",
    "Team Rocket's Ariana",
    "Team Rocket's Ariana",
    "Team Rocket's Giovanni",        # 4x — Rocket power
    "Team Rocket's Giovanni",
    "Team Rocket's Giovanni",
    "Team Rocket's Giovanni",
    "Team Rocket's Petrel",          # 4x — Rocket search
    "Team Rocket's Petrel",
    "Team Rocket's Petrel",
    "Team Rocket's Petrel",
    # Energy (16 cards)
    "Basic {D} Energy",              # 16x Darkness Energy
    "Basic {D} Energy",
    "Basic {D} Energy",
    "Basic {D} Energy",
    "Basic {D} Energy",
    "Basic {D} Energy",
    "Basic {D} Energy",
    "Basic {D} Energy",
    "Basic {D} Energy",
    "Basic {D} Energy",
    "Basic {D} Energy",
    "Basic {D} Energy",
    "Basic {D} Energy",
    "Basic {D} Energy",
    "Basic {D} Energy",
    "Basic {D} Energy",
]


def load_card_id_map(csv_path: str = '/kaggle/input/EN_Card_Data.csv') -> dict[str, int]:
    """Map card names to their Card IDs from the official CSV."""
    name_to_id = {}
    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            name = row.get('Card Name', '').strip()
            cid_str = row.get('Card ID', row.get('card_id', '0')).strip()
            try:
                cid = int(cid_str)
            except ValueError:
                continue
            if name not in name_to_id:
                name_to_id[name] = cid
    return name_to_id


def get_deck_card_ids(name_to_id: dict[str, int]) -> list[int]:
    """Convert deck card names to card IDs."""
    ids = []
    for name in DECK_CARD_NAMES:
        cid = name_to_id.get(name)
        if cid is not None:
            ids.append(cid)
    # Pad to 60 if needed (shouldn't happen with correct card names)
    while len(ids) < 60 and ids:
        ids.append(ids[-1])
    return ids[:60]


# ═══════════════════════════════════════════════════════════════════════════════
# Observation Parser
# ═══════════════════════════════════════════════════════════════════════════════

class GameObservation:
    """Parsed game state from the official engine's obs_dict."""

    def __init__(self, obs_dict: dict):
        self.raw = obs_dict
        self.select = obs_dict.get('select', None)
        self.turn = obs_dict.get('turn', 1)
        self.my_side = obs_dict.get('my_side', {})
        self.opp_side = obs_dict.get('opp_side', {})
        self.phase = obs_dict.get('phase', '')
        self.first_player = obs_dict.get('first_player', None)
        self.is_first = obs_dict.get('is_first', False)

    @property
    def is_deck_selection(self) -> bool:
        return self.select is None

    @property
    def options(self) -> list:
        if self.select is None:
            return []
        return self.select.get('option', [])

    @property
    def can_attack(self) -> bool:
        # P2 can attack on turn 1; both can attack from turn 2+
        return self.turn > 1 or not self.is_first

    @property
    def my_active(self) -> Optional[dict]:
        return self.my_side.get('active')

    @property
    def opp_active(self) -> Optional[dict]:
        return self.opp_side.get('active')

    @property
    def my_bench(self) -> list:
        return self.my_side.get('bench', [])

    @property
    def my_hand(self) -> list:
        return self.my_side.get('hand', [])

    @property
    def my_energy_attached(self) -> bool:
        return self.my_side.get('energy_attached', False)


# ═══════════════════════════════════════════════════════════════════════════════
# Threat-Aware Action Selection (ported from baseline_agent.py)
# ═══════════════════════════════════════════════════════════════════════════════

def _parse_damage(dmg_str: str) -> int:
    if not dmg_str or dmg_str.strip() in ('n/a', '', '0'):
        return 0
    base = re.sub(r'[×+].*', '', dmg_str).strip()
    try:
        return int(base)
    except ValueError:
        return 0


def _parse_hp(pokemon: Optional[dict]) -> int:
    if pokemon is None:
        return 0
    hp = pokemon.get('hp', 0)
    if isinstance(hp, str):
        try:
            return int(hp)
        except ValueError:
            return 0
    return hp


def _current_hp(pokemon: Optional[dict]) -> int:
    """Estimate current HP (max - damage)."""
    if pokemon is None:
        return 0
    hp = _parse_hp(pokemon)
    dmg = pokemon.get('damage', 0)
    if isinstance(dmg, str):
        try:
            dmg = int(dmg)
        except ValueError:
            dmg = 0
    return max(0, hp - dmg)


def _calculate_threat(my_active: Optional[dict], opp_active: Optional[dict]) -> dict:
    """Quick threat assessment: can I KO? Can opponent KO me?"""
    if my_active is None or opp_active is None:
        return {'i_can_ko': False, 'opp_can_ko': False}

    my_dmg = _parse_damage(my_active.get('attack_damage', '0'))
    opp_dmg = _parse_damage(opp_active.get('attack_damage', '0'))
    opp_hp = _current_hp(opp_active)
    my_hp = _current_hp(my_active)

    return {
        'i_can_ko': my_dmg >= opp_hp,
        'opp_can_ko': opp_dmg >= my_hp,
        'my_dmg': my_dmg,
        'opp_dmg': opp_dmg,
        'opp_hp': opp_hp,
        'my_hp': my_hp,
    }


def select_action(obs: GameObservation) -> list[int]:
    """
    Main action selection using threat-aware heuristic.

    Priority order:
    1. KO opponent if possible (GUARANTEED_KO)
    2. Retreat if active would die (SURVIVAL)
    3. Evolve active if possible (DEVELOP)
    4. Play basics to bench (DEVELOP)
    5. Attach energy to active (DEVELOP)
    6. Attack (FALLBACK)
    7. Pass (FALLBACK)
    """
    options = obs.options
    if not options:
        return [0]

    threat = _calculate_threat(obs.my_active, obs.opp_active)

    # Analyze each option
    best_idx = 0
    best_priority = 999

    for i, opt in enumerate(options):
        opt_type = opt.get('type', '').lower()
        priority = 100  # default low priority

        if opt_type in ('attack', 'use_attack'):
            if threat['i_can_ko']:
                priority = 0  # GUARANTEED_KO
            elif obs.can_attack and threat['my_dmg'] > 0:
                priority = 5  # ATTACK_FAVORABLE
            else:
                priority = 8  # ATTACK_ANY
        elif opt_type == 'retreat':
            if threat['opp_can_ko'] and len(obs.my_bench) > 0:
                priority = 1  # SURVIVAL_RETREAT
            else:
                priority = 7  # RETREAT_LOW_HP
        elif opt_type in ('evolve', 'evolution'):
            priority = 2  # EVOLVE
        elif opt_type in ('play_basic', 'bench', 'play_to_bench'):
            priority = 3  # PLAY_BASIC
        elif opt_type in ('attach_energy', 'energy_attach'):
            if not obs.my_energy_attached:
                priority = 4  # ATTACH_ENERGY
            else:
                priority = 9
        elif opt_type == 'pass':
            priority = 10  # PASS

        if priority < best_priority:
            best_priority = priority
            best_idx = i

    return [best_idx]


# ═══════════════════════════════════════════════════════════════════════════════
# Main Agent Entry Point
# ═══════════════════════════════════════════════════════════════════════════════

# Cache for deck card IDs (loaded once on first call)
_deck_ids: Optional[list[int]] = None


def agent(obs_dict: dict) -> list[int]:
    """
    Official agent entry point for Kaggle submission.

    Called repeatedly by the game engine:
    - First call: obs['select'] is None → return 60 card IDs (deck)
    - Subsequent calls: obs['select'] has options → return chosen indices
    """
    global _deck_ids

    obs = GameObservation(obs_dict)

    # Deck selection (first call only)
    if obs.is_deck_selection:
        if _deck_ids is None:
            # Load card ID mapping from the competition's data file
            name_to_id = load_card_id_map()
            _deck_ids = get_deck_card_ids(name_to_id)
        return _deck_ids

    # Action selection
    return select_action(obs)


# ═══════════════════════════════════════════════════════════════════════════════
# Local Testing (not used in Kaggle environment)
# ═══════════════════════════════════════════════════════════════════════════════

if __name__ == '__main__':
    # Test deck loading
    try:
        name_to_id = load_card_id_map('/workspace/EN_Card_Data.csv')
    except FileNotFoundError:
        name_to_id = load_card_id_map('EN_Card_Data.csv')

    deck_ids = get_deck_card_ids(name_to_id)
    print(f"Deck: {len(deck_ids)} cards loaded")
    print(f"Sample IDs: {deck_ids[:5]}")

    # Verify card names
    id_to_name = {v: k for k, v in name_to_id.items()}
    for cid in deck_ids[:10]:
        print(f"  ID {cid}: {id_to_name.get(cid, 'UNKNOWN')}")

    # Test action selection with mock observation
    mock_obs = {
        'select': {
            'option': [
                {'type': 'attack', 'damage': 160},
                {'type': 'retreat'},
                {'type': 'pass'},
            ]
        },
        'turn': 2,
        'is_first': False,
        'my_side': {
            'active': {'hp': 280, 'damage': 0, 'attack_damage': '160'},
            'bench': [{'hp': 230, 'damage': 0}],
            'hand': [],
            'energy_attached': False,
        },
        'opp_side': {
            'active': {'hp': 110, 'damage': 0, 'attack_damage': '90'},
        },
    }
    result = agent(mock_obs)
    print(f"\nAction test: chose index {result} from 3 options")
    print(f"  (0=attack, 1=retreat, 2=pass)")
